#########################################################
# This file has been automatically generated by gem2tgz #
#########################################################
# -*- encoding: utf-8 -*-
# stub: faraday 0.9.2 ruby lib

Gem::Specification.new do |s|
  s.name = "faraday"
  s.version = "0.9.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Rick Olson"]
  s.date = "2015-10-05"
  s.email = "technoweenie@gmail.com"
  s.files = ["LICENSE.md", "README.md", "lib/faraday.rb", "lib/faraday/adapter.rb", "lib/faraday/adapter/em_http.rb", "lib/faraday/adapter/em_http_ssl_patch.rb", "lib/faraday/adapter/em_synchrony.rb", "lib/faraday/adapter/em_synchrony/parallel_manager.rb", "lib/faraday/adapter/excon.rb", "lib/faraday/adapter/httpclient.rb", "lib/faraday/adapter/net_http.rb", "lib/faraday/adapter/net_http_persistent.rb", "lib/faraday/adapter/patron.rb", "lib/faraday/adapter/rack.rb", "lib/faraday/adapter/test.rb", "lib/faraday/adapter/typhoeus.rb", "lib/faraday/autoload.rb", "lib/faraday/connection.rb", "lib/faraday/error.rb", "lib/faraday/middleware.rb", "lib/faraday/options.rb", "lib/faraday/parameters.rb", "lib/faraday/rack_builder.rb", "lib/faraday/request.rb", "lib/faraday/request/authorization.rb", "lib/faraday/request/basic_authentication.rb", "lib/faraday/request/instrumentation.rb", "lib/faraday/request/multipart.rb", "lib/faraday/request/retry.rb", "lib/faraday/request/token_authentication.rb", "lib/faraday/request/url_encoded.rb", "lib/faraday/response.rb", "lib/faraday/response/logger.rb", "lib/faraday/response/raise_error.rb", "lib/faraday/upload_io.rb", "lib/faraday/utils.rb"]
  s.homepage = "https://github.com/lostisland/faraday"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "HTTP/REST API client library."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<multipart-post>, ["< 3", ">= 1.2"])
    else
      s.add_dependency(%q<multipart-post>, ["< 3", ">= 1.2"])
    end
  else
    s.add_dependency(%q<multipart-post>, ["< 3", ">= 1.2"])
  end
end
